### ISSUE TITLE
Remind: Broken @

### ISSUE THREAD

**Issue by RosaEscura** [Gerpiili369/GerpBot#11]
![image](https://user-images.githubusercontent.com/38073849/39607184-3b8ea1f0-4f42-11e8-8ef0-fa499bb8764f.png)

Nyt ei tullu sitä @roolia toho viesti osioo vaa pelkkä embed eli tolla ei sais huomioo.

**Comment by Gerpiili369** [comment]
Fixed in https://github.com/Gerpiili369/GerpBot/commit/363758ab19a5a5910e18699d8e868ea96c2c3f54
