### ISSUE TITLE
Add channel info feature

### ISSUE THREAD

**Issue by RosaEscura** [Gerpiili369/GerpBot#16]
Add "@GerpBot channel" feature that tells (by default) info about the current channel, such as channel creation time and players' names that are in that channel, if the channel is restricted. A different channel can also be specified with a different channel name after the word channel, eg. "@GerpBot channel #general".

**Comment by Gerpiili369** [comment]
Added to [develop](/Gerpiili369/GerpBot/tree/develop) in ab044be16e326b26cbdf7879df06f5ddff173ffb.
